// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Runtime config interface
interface RuntimeConfig {
  VITE_SUPABASE_URL: string;
  VITE_SUPABASE_PUBLISHABLE_KEY: string;
}

// Get config from runtime (injected by entrypoint.sh) or build-time env
const getRuntimeConfig = (): RuntimeConfig => {
  // Check if runtime config exists (from entrypoint.sh)
  if (typeof window !== 'undefined' && (window as any).__RUNTIME_CONFIG__) {
    const config = (window as any).__RUNTIME_CONFIG__;
    console.log('✅ Using runtime config from container environment');
    return config;
  }

  // Fallback to build-time environment variables
  console.log('⚠️ Using build-time environment variables (fallback)');
  return {
    VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL,
    VITE_SUPABASE_PUBLISHABLE_KEY: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
  };
};

const config = getRuntimeConfig();

// Validate config
if (!config.VITE_SUPABASE_URL || !config.VITE_SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Supabase credentials not found!');
  throw new Error('Missing Supabase credentials. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY');
}

console.log('📡 Supabase URL:', config.VITE_SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  config.VITE_SUPABASE_URL,
  config.VITE_SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
